const products = [
    {
      id: 1,
      title: 'Casio MTP-1314PL-8AVEF Classic',
      price: 6490,
      img: './images/casio.jpg',
      desc: `Funkcije: Datum, 
      Garancija na bateriju: 25 meseci, 
      Garancija na mehanizam:	25 meseci, 
      Kućište - materijal:	Hirurški čelik
      Mehanizam - vrsta:	Kvarcni,
      Narukvica - materijal:	Koža,
      Prečnik kućišta:	45mm,
      Prikaz sata:	Analogni`,
    },
    {
      id: 2,
      title: 'Daniel Klein DK13315-4',
      price:  7950 ,
      img: './images/dk.jpg',
      desc: `Vodootpornost:	Do 3 ATM,
      Brendovi: DANIEL KLEIN,
      Garancija na bateriju:	1 godina,
      Garancija na mehanizam:	25 meseci,
      Kućište - materijal:	Metal,
      Mehanizam - vrsta:	Kvarcni,
      Narukvica - materijal:	Metal`,
    },
    {
      id: 3,
      title: 'Festina F20445/5',
      price: 12190,
      img: './images/festina.jpg',
      desc: `Funkcije: Datum i Doba dana,
      Garancija na bateriju:	25 meseci,
      Garancija na mehanizam:	25 meseci,
      Kućište - materijal:	Hirurški čelik,
      Mehanizam - vrsta:	Kvarcni,
      Narukvica - materijal:	Hirurški čelik,
      Prečnik kućišta:	43mm`,
    },
    {
      id: 4,
      title: 'Diesel DZ1807',
      price: 24290,
      img: './images/diesel.jpg',
      desc: `Vodootpornost: 5 ATM,
      Brendovi: DIESEL,
      Garancija na bateriju: 25 meseci,
      Garancija na mehanizam: 25 meseci,
      Kućište - materijal: Hirurški čelik,
      Mehanizam - vrsta: Kvarcni,
      Narukvica - materijal: Silikon,
      Prečnik kućišta: 46mm`,
    },
    {
      id: 5,
      title: 'G-Shock GA-100-1A1ER',
      price: 14490,
      img: './images/gshock.jpg',
      desc: `Funkcije: Alarm, Dani u nedelji, Datum, Doba dana, LED svetlo, Štoperica, Svetsko vreme i Tajmer,
      Garancija na bateriju: 25 meseci,
      Garancija na mehanizam: 25 meseci,
      Kućište - materijal: Smola,
      Mehanizam - vrsta: Kvarcni,
      Narukvica - materijal: Smola,
      Prikaz sata: Analogno-Digitalni`,
    },
    {
      id: 6,
      title: 'Festina F16760/4 Festina 169',
      price: 17000,
      img: './images/festinacrni.jpg',
      desc: `Funkcije: Datum, Doba dana i Štoperica,
      Garancija na bateriju: 25 meseci,
      Garancija na mehanizam: 25 meseci,
      Kućište - materijal: Hirurški čelik,
      Mehanizam - vrsta: Kvarcni,
      Narukvica - materijal: Koža,
      Prečnik kućišta: 44mm,
      Prikaz sata: Analogni`,
    },
    {
      id: 7,
      title: 'Seiko SUR447P1 Classic',
      price: 27500,
      img: './images/seiko.jpg',
      desc: `Funkcije: Dani u nedelji i Datum,
      Garancija na bateriju: 25 meseci,
      Garancija na mehanizam: 25 meseci,
      Kućište - materijal: Hirurški čelik,
      Mehanizam - vrsta: Kvarcni,
      Narukvica - materijal: Koža,
      Prečnik kućišta: 40.2mm,
      Prikaz sata: Analogni`,
    },
    {
      id: 8,
      title: 'Daniel Klein DK13294-5',
      price: 5900,
      img: './images/dkzel.jpg',
      desc: `Vodootpornost: Do 3 ATM,
      Brendovi: DANIEL KLEIN,
      Garancija na bateriju: 1 godina,
      Garancija na mehanizam: 25 meseci,
      Kućište - materijal: Metal,
      Mehanizam - vrsta: Kvarcni,
      Narukvica - materijal: Metal`,
    },
    
  ];
  export default products;